AWSTemplateFormatVersion: "2010-09-09"
Description: An example template for a creating volume.
Resources: 
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      VolumeType: VolumeType1
      Size: VolumeSize1
      AvailabilityZone: Azs
      Encrypted: Encrypted1
      Tags:
      - Key: Name
        Value: test-volume
      
